### ISSUE TITLE
CVE detected in SonarLint IntelliJ plugin 6.3.1.40498 - Upgrade omnisharp-roslyn?

### ISSUE THREAD

**Issue by kphilly1** [SonarSource/sonarlint-omnisharp#101]
When performing a security scan of SonarLint IntelliJ plugin 6.3.1.40498, a critical vulnerability (related to an outdated Microsoft DLL) was detected in one of the dependencies in the project.

We believe that it may be related to Omnisharp, which is specified in the project’s gradle.properties file, as it specifies the following:

omnisharpVersion=v1.37.11

This particular omnisharp version appears to correspond to the omnisharp-roslyn project, which appears to use csharp, dotnet, and dotnet-sdk. Most likely, these are referring the offending Microsoft DLL, which appears to be the .NET Core System.Text.Encodings.Web.dll v4.700.20.21406:

![image](https://user-images.githubusercontent.com/4879243/146096081-8dde7b78-4eca-4b12-8776-dd872d4a38e7.png)

Notice that “High Policy Threat” is level 9 (within 2 policies).

However, v4.700.20.27001 of the DLL does not have the vulnerability:

![image](https://user-images.githubusercontent.com/4879243/146096099-e60d053e-1851-4b7d-b6d5-824259f1cd6c.png)

The most recent version of omnisharp-roslyn appears to be v1.37.17.

Is it possible for sonarlint-intellij plugin to bump the omnisharpVersion to 1.37.17 in gradle.properties to see if the issue is resolved?

If the sonarlint-roslyn project could also make any related updates as well (such that newer version - 4.700.20.27001 - of the .NET Core System.Text.Encodings.Web.dll is used), it would be greatly appreciated.

Thank you very much for your help!

**Comment by rita-sonarsource** [comment]
Fixed, will be released as part of 1.1.
