### ISSUE TITLE
High Memory usage over time

### ISSUE THREAD

**Issue by dotdiego** [SonarSource/sonarlint-omnisharp#116]
Hello,

I have an issue with the Jetbrains Rider plugin.
After a long usage time the Omnisharp process started by Sonarlint starts consuming 4 to 5Gb of RAM instead of a clas.

I've used Jetbrains Rider 2021.3.4 and the latest 2022.1 version.
The problems occurs with version 6.6.0.45106 and 6.7.0.45926 of Sonarlint.
I keep downgrading to the latest functional version for me 6.5.1.43866.

What kind of logs can i provide you to give you more informations ?

Regards,

**Comment by ugras-ergun-sonarsource** [comment]
Hi @dotdiego,
Sorry for the late reply. We weren't able to reproduce the issue. Does this problem still exist? If it is, could you please answer these questions? 

1) Which OS do you use? 
2) How large is your solution, and how many projects do your solution have?  
3) Which version of .Net do your projects target?

Best,

**Comment by dotdiego** [comment]
Hello,

I never updated back again, but it occured everytime I reinstalled those versions of sonarlint.
We have a single solution with 14 C#/.NET 4.6.1 projects.

Now i've updated to Rider 2022.1.2, I could try to update Sonarlint again.

**Comment by dotdiego** [comment]
Seems better now with latest version and Rider 2022.2.*
