### ISSUE TITLE
Update embedded C# analyzer to 9.13.0.79967

### ISSUE THREAD

**Issue by sophio-japharidze-sonarsource** [SonarSource/sonarlint-omnisharp#178]
See https://sonarsource.atlassian.net/browse/SLI-1156

Release notes for the analyzer are [here](https://github.com/SonarSource/sonar-dotnet/releases/tag/9.13.0.79967)

**Comment by thahnen** [comment]
Hi @sophio-japharidze-sonarsource, can we now merge the PR with the .NET 8 test?
