### ISSUE TITLE
Specify the protocol for the SonarLint rules configuration service

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-omnisharp#3]
### Description

Agree the endpoint name and format of the json used by the Java plugin to pass rules configuration and parameters to the .NET plugin.

? pass configuration for all rules, or just those that are currently activate?
? are there any other server settings that need to be passed?

**Comment by rita-sonarsource** [comment]
POST `/sonarlint/config`
```
{ 
   "rules" : [
     "ruleId" : "S123",
     "isEnabled" true,
     "params" : {
        "key" : "value"
     }
   ]
}
```

**Comment by rita-sonarsource** [comment]
Following #84 , the new api contains only **enabled** rules.

POST `/sonarlint/config`
```
{ 
   "activeRules" : [
      {
         "ruleId" : "S123",
         "params" : {
            "key" : "value"
         }
     }
   ]
}
```
