### ISSUE TITLE
Test upgrade to OmniSharp v1.37.11

### ISSUE THREAD

**Issue by rita-sonarsource** [SonarSource/sonarlint-omnisharp#56]
#### Description

Check if we can upgrade to the latest omnisharp version: https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.37.11

##### Notes:
We previously couldn't because the release was referencing a version of `Microsoft.CodeAnalysis` nuget package that was not available in the public nuget feed.

**Comment by duncanp-sonar** [comment]
Looks like v1.37.11 is using the latest [_prerelease_](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces/3.11.0-1.final) version of Roslyn (v3.11.0-1.final).
Our plugin does work with OmniSharp v1.37.11 if we switch to using that Roslyn version.
