### ISSUE TITLE
Create SonarLint codecheck service

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-omnisharp#6]
### Description

Create a new service endpoint based on the existing `codecheck` service that passes requests to the custom SonarLint diagnostic worker.

- [x] create service endpoint. 
- [x] unit tests

**Comment by rita-sonarsource** [comment]
API:
POST `/sonarlint/codecheck`
```
{ 
   "FileName" : "test.cs"
}
```
