### ISSUE TITLE
Rules parameters are ignored

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-omnisharp#82]
### Description

Rules parameters are passed to the analysers but are not being used. Also, the log is full of warnings about missing files.

#### Background

The underlying problem is a bug in the analyzers - they are trying to read the SonarLint.xml from disc, rather than using the Roslyn API.

There a couple of obvious solutions:
1) change the analyzers to use the Roslyn API.
2) work round the issue in our plugin by saving the file to disc.

Option (2) is superficially attractive, but has a number of problems: 
* creating temporary files has previously caused problems on different OSes e.g. permissions, file locking, virus checking
* analyses can run in parallel, and the configuration could change between each run. We'd either have to create a separate file for each run, or track whether the configuration had changed and write/update a single file and deal with locking/concurrency issues.

**Comment by rita-sonarsource** [comment]
Fixed on the analyzer side: https://github.com/SonarSource/sonar-dotnet/pull/4616
